image: python:latest

before_script:
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - pip install -r requirements_dev.txt


python36:
    image: python:3.6
    stage: test
    script:
        - tox -e py36

python37:
    image: python:3.7
    stage: test
    script:
        - tox -e py37

python38:
    image: python:3.8
    stage: test
    script:
        - tox -e py38

lint:
    image: python
    stage: test
    script:
        - tox -e black
